version: '3'
services:
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: rails
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
